// build.mjs — esbuild bundler for theme TypeScript sources.
//
// Each entry in src/entries/ compiles to a standalone IIFE bundle written
// to its historical location so no Hugo template changes are needed:
//   - animation modules  -> static/js/*.js  (loaded via <script defer>)
//   - main / menu        -> assets/js/*.js  (fed into the Hugo Pipes bundle)
//
// Run:  node build.mjs           one-shot
//       node build.mjs --watch   rebuild on change
import { build, context } from "esbuild";

const BANNER =
  "// GENERATED from src/ by build.mjs — do not edit this file directly.";

/** @type {Array<{ in: string, out: string }>} */
const ENTRIES = [
  { in: "src/entries/crt-aurora.ts", out: "static/js/crt-aurora" },
  { in: "src/entries/particles.ts", out: "static/js/particles" },
  { in: "src/entries/cursor-fx.ts", out: "static/js/cursor-fx" },
  { in: "src/entries/main.ts", out: "assets/js/main" },
  { in: "src/entries/menu.ts", out: "assets/js/menu" },
];

/** @type {import("esbuild").BuildOptions} */
const shared = {
  bundle: true,
  format: "iife",
  target: "es2020",
  // Hugo (--minify) and the Pipes bundle handle minification; keep committed
  // output readable and diff-friendly.
  minify: false,
  sourcemap: false,
  banner: { js: BANNER },
  logLevel: "info",
};

async function run() {
  const watch = process.argv.includes("--watch");

  const configs = ENTRIES.map((e) => ({
    ...shared,
    entryPoints: [e.in],
    outfile: `${e.out}.js`,
  }));

  if (watch) {
    const ctxs = await Promise.all(configs.map((c) => context(c)));
    await Promise.all(ctxs.map((c) => c.watch()));
    console.log("[build] watching src/ for changes…");
  } else {
    await Promise.all(configs.map((c) => build(c)));
    console.log(`[build] compiled ${ENTRIES.length} entries`);
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
